CREATE TABLE reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    destination_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);